# Generated by Django 5.2.4 on 2025-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gold', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('armor', models.CharField(blank=True, max_length=100, null=True)),
                ('weapon', models.CharField(blank=True, max_length=100, null=True)),
                ('off_hand', models.CharField(blank=True, max_length=100, null=True)),
                ('ring1', models.CharField(blank=True, max_length=100, null=True)),
                ('ring2', models.CharField(blank=True, max_length=100, null=True)),
                ('ring3', models.CharField(blank=True, max_length=100, null=True)),
                ('pet', models.CharField(blank=True, max_length=100, null=True)),
                ('total_work_hour', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
